services:
  mysql-db:
    image: mysql
    container_name: mysql-db
      #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

# DON'T USE THIS ON PRODUCTION!!'
